package splash

import "fmt"

const splash = `
-------------------------------------------------------------------------------
                             Discord Reposter Bot
-------------------------------------------------------------------------------
MMMMMMMMMMMMMs:NNmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMM- shmNyMMNMMMMMMMMMMMMMMNmddmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMh+:-/+/hhy-dMMMMMMMMMMdoyyhs  +ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNho--/'++NMMMMMMMMdsdNNMy  mddoMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMd-     ./mMMMMMMh.dNNM+'-MMd+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM-       -NMMMMMMh/ooos'':smmyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMN//'     +MMMMMMMm/hdhs:-yNhyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMo-:     .yMMMMMMM+NhysNMMN  mMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMM-       -NddNMMs+/' '-/. -MMMMMMMMMMMMo-Mo/dyyMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMm         / +hmhd+.      oNMMMMMMMMMMMN  -  ' /dMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMd         ./:d  .'-hhy+- /NdmMMMMMMMMMN        sMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMM         yMy-     /NMMMdyhhsdNMMMMMMM/      .sNMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMy       oym'   s:  -mMMMMMNo/MMMMMhy-     .yMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNyssshNNs'    mMo-+./ydmMMMMMMMMN-o:    hNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNmmdd+'     -yhmdMMNdy+o/+ym+ymNM:    /MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMs          /MMMMMMNmNdsNoo+/'  '-MMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMd:        'sMmmMMMMMm+/'.mNN   -NMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMoy'      shm//dMdmh+-y/+-Nm .hMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMsohs:'/o+mMMdhds/' /sdyd:'hdMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMd.ydmNMNmdMmy+'   :sssso+ NMMMMMMMMMMMMMMMMMMMMMMMM         
                     
                             "YOUR MOVE CREEP."
`

//Showtime is just a good old ASCII art
func Showtime() {
	fmt.Println(splash)
}
